Adds functions needed to generate an array containing 25 objects
htmlacademy-javascript/1572931-kekstagram-23 pull request #3
Opened 2021-06-06 12:11 UTC by life-invader

2021-06-06 14:43 UTC, o-bender requested changes

2021-06-06 14:43 UTC, o-bender commented on js/main.js
> +  function generateTestComment () {
лучше так 
```
function generateTestComment() {
}

function generateTestArray() {
}
```
Без необходимости лучше не делать функции вложенными. В нашем случае это просто уменьшает читабельность. В более сложных случаях это можешь сильно влиять я производительность. И делать поиск ошибок ужасно трудной задачей.

2021-06-06 14:43 UTC, o-bender commented on js/main.js
> +console.log(TEST_ARRAY);
Эта и другие ошибки линтера :)

2021-06-06 17:22 UTC, life-invader commented on js/main.js
> +console.log(TEST_ARRAY);
Ты имеешь ввиду ошибку линтера из-за консоль лога? Ты кажется сказал пока вообще не обращать внимания на ошибки линтера. И еще, остальные ошибки линтера из-за 2 файлов, которые я принял от академии: 'check-string-length' и 'get-random-positive-integer'. Может их вообще удалить из коммита и никуда не пушить? И как это можно сделать ?

2021-06-06 17:22 UTC, life-invader commented on js/main.js
> +console.log(TEST_ARRAY);
Ты имеешь ввиду ошибку линтера из-за консоль лога? Ты кажется сказал пока вообще не обращать внимания на ошибки линтера. И еще, остальные ошибки линтера из-за 2 файлов, которые я принял от академии: 'check-string-length' и 'get-random-positive-integer'. Может их вообще удалить из коммита и никуда не пушить? И как это можно сделать ?

2021-06-06 20:59 UTC, o-bender commented on js/main.js
> +console.log(TEST_ARRAY);
Если они тебе не нужны. То просто удали файлы и сделай коммит. Если линтер ругается на такую ерунду как console.log, то почему не исправить?)

2021-06-07 12:05 UTC, life-invader commented on js/main.js
> +console.log(TEST_ARRAY);
Консоль лог удалил, теперь линтер ругается, что TEST_ARRAY assigned but never used.

2021-06-07 19:58 UTC, o-bender commented on js/main.js
> +console.log(TEST_ARRAY);
Ладно. Пока так пойдёт

2021-06-07 19:58 UTC, merged