adds an image manipulation form
htmlacademy-javascript/1572931-kekstagram-23 pull request #6
Opened 2021-06-22 15:35 UTC by life-invader

С noUislider не разобрался. Остальное просто работает.

2021-06-22 16:50 UTC, o-bender requested changes
Вообще советовал бы удалить пока что nouislider из package.json. Потому что в 9 задании придут обновления от кекса и там будет nouislider той версии которой хочет академия. А код с ним связанный закомментируй.

2021-06-22 16:50 UTC, o-bender commented on js/form.js
> +const body = document.querySelector('body');
для этого есть document.body

2021-06-22 16:50 UTC, o-bender commented on js/form.js
> +import '../node_modules/nouislider/dist/nouislider.js'; // <= Почему он лежит в нод модулях
слайдер в 9 модуле будет. там про него нормально расскажут

2021-06-22 16:50 UTC, o-bender commented on js/form.js
> +const hashtagsNumber = 5;
Переведи в верхний регистр.
И константы должны объявляться сразу после импортов.

2021-06-22 16:50 UTC, o-bender commented on js/form.js
> +const re = /^#[A-Za-zА-Яа-я0-9]{1,19}$/;
Лучше выбрать какое-нибудь более понятное имя

2021-06-22 16:50 UTC, o-bender commented on js/form.js
> +  let scale = scaleValue.value.replace(/[^a-zа-яё0-9\s]/gi, ' ');
тут можно обойтись:
```
let scale = Number(scaleValue.value.replace(/[^\d]/g, ' '));
```
В замене на пробел не вижу смысла.

2021-06-22 16:50 UTC, o-bender commented on js/form.js
> +    if (!(+scale <= 25)) {
+scale тоже не будет нужен если напишешь как я указал в предыдущем комменте

2021-06-22 16:50 UTC, o-bender commented on js/form.js
> +      imgPreview.style = `transform: scale(0.${scale})`;
эта и следующая строка повторяются несколько раз в этой функции. стоит вынести их в отдельную функцию

2021-06-22 16:50 UTC, o-bender commented on js/form.js
> +stepSlider.noUiSlider.on('update', function (values, handle) {
функция через слово function. уверен, что она такая тут нужна?

2021-06-22 16:50 UTC, o-bender commented on js/form.js
> +  console.log(noUiSlider);
консоль лог

2021-06-22 16:50 UTC, o-bender commented on js/form.js
> +  const hashtags = hashtagInput.value.toLowerCase().split(' ');
добавь ещё trim перед split

2021-06-22 16:50 UTC, o-bender commented on js/form.js
> +  for (let i = 0; i < hashtags.length; i++) {
ещё как вариант можно создать список тегов уже прошедших валидацию и сверять следующий тег с ним.
```
const validTags = [];
for (let tag of hashtags) {
    if (validTags.includes(tag)) {
       hashtagInput.setCustomValidity("Error")
    }
}
```
Тут решать тебе, как больше нравится

2021-06-22 16:50 UTC, o-bender commented on js/form.js
> +  if ( !(checkCommentLength(commentValue, COMMENT_LENGTH)) ) {
если поменять местами секции из if и else, то можно отказаться от отрицания в условии

2021-06-23 13:28 UTC, life-invader commented on js/form.js
> +  let scale = scaleValue.value.replace(/[^a-zа-яё0-9\s]/gi, ' ');
1) Как вообще работают эти два выражения. В моем случае с "/[^a-zа-яё0-9\s]/gi" мы ищем все кроме букв, цифр и пробелов глобально, без учета регистра, верно ?
2) В твоем мы ищем все кроме цифр, знак "^" в квадратных скобках означает отрицание ? И мы находим лишние символы и убираем их с помощью replace().
3) Если нет смысла замены на пробел, то как мне получить value инпута и оставить только цифру ?

2021-06-23 16:34 UTC, o-bender commented on js/form.js
> +const body = document.body;
я к тому, что нет смысла делать глобальную переменную body, когда body и так всегда под рукой в document.body. Но тут хозяин барин, дело вкуса.

2021-06-23 16:34 UTC, o-bender commented on js/form.js
> +// Функция изменения масштаба
Можешь не переделывать если не хочешь. Но если интересно, то я бы сделал примерно так:
```
const scaleDirection = {
  up: 1,
  down: -1,
};

const scaleThreshold = {
  max: 100,
  min: 25,
};

const scaleUpElement = document.querySelector('.scale__control--bigger');
const scaleDownElement = document.querySelector('.scale__control--smaller');

const setScale = (scale) => {
  imgPreview.style = `transform: scale(${scale / 100})`;
  scaleValue.value = `${scale}%`;
};

const changeScale = (direction) => {
  const scale = Number(scaleValue.value.replace(/[^\d]/g, ''));
  if (scale >= scaleThreshold.max && direction === scaleDirection.up
   || scale <= scaleThreshold.min && direction === scaleDirection.down) {
    return;
  }
  setScale(scale  + 25 * direction);
};

scaleUpElement.addEventListener('click', () => changeScale(scaleDirection.up));
scaleDownElement.addEventListener('click', () => changeScale(scaleDirection.down));
```

2021-06-23 16:34 UTC, o-bender commented on js/form.js
> +    scale -= 25;
Магически значения 25 и 100. Нужно вынести в константы.

2021-06-23 16:34 UTC, o-bender commented on js/form.js
> +  if (action === 'decrease') {
decrease и increase магические значения. Нужно вынести в константы.

2021-06-23 16:34 UTC, o-bender commented on js/form.js
> +      imgPreview.style = `transform: scale(${scale / 100})`;
Вот это не магическое значение. Пусть живёт :)

2021-06-23 16:34 UTC, o-bender commented on js/form.js
> +
лишняя пустая строка

2021-06-23 16:34 UTC, o-bender commented on js/form.js
> +  if (checkCommentLength(commentValue, COMMENT_LENGTH)) {
ты меня возненавидишь наверное :) В оправдание я не требую переделывать :) Просто хочу показать лучший вариант:
```
const errors = {
   maxCommentLength: `Максимальная длина комментария ${COMMENT_LENGTH} символов`
};

commentField.addEventListener('input', () => {
  const errorMessage = checkCommentLength(commentField.value, COMMENT_LENGTH) : '' ? errors.maxCommentLength;
  commentField.setCustomValidity(errorMessage);
  commentField.reportValidity();
});
```

2021-06-23 16:34 UTC, merged